[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/autodate.vim'
hook_add = '''
    let g:autodate_keyword_pre = 'Modified:'
    let g:autodate_keyword_post = '\.'
    let g:autodate_format = '%Y-%m-%d'
    let g:autodate_lines = 10
    let g:autodate_start_line = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_char = '│'
    let g:indentLine_leadingSpaceChar = ' '
    let g:indentLine_first_char = '│'
    let g:indentLine_showFirstIndentLevel = 1
    let g:indentLine_leadingSpaceEnabled = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set laststatus=2
    set noshowmode
    let g:lightline = {
    \    'subseparator': { 'left': "\u2502", 'right': "\u2502" }
    \}
'''

[[plugins]]
repo = 'junk-e/identity.vim'

[[plugins]]
repo = 'icymind/NeoSolarized'
